services:
  frontend:
    build:
      context: ./react-ts
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5454
    networks:
      - workout-net
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5454:5454"
    depends_on:
      - db
    env_file:
      - ./backend/secrets.env
    environment:
      - DB_URL=jdbc:mysql://db:3306/workout
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - workout-net
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=workout
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - workout-net

volumes:
  mysql_data:

networks:
  workout-net:
